apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-1-data
  namespace: consul-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---

apiVersion: v1
kind: Service
metadata:
  name: consul-1-ui
  namespace: consul-1
spec:
  selector:
    app: consul-1
  ports:
    - name: http
      protocol: TCP
      port: 8500
      targetPort: 8500
    - name: dns
      protocol: UDP
      port: 8600
      targetPort: 8600
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul-1
  namespace: consul-1
spec:
  serviceName: consul-1
  replicas: 1
  selector:
    matchLabels:
      app: consul-1
  template:
    metadata:
      labels:
        app: consul-1
    spec:
      containers:
        - name: consul-1
          image: consul:1.15.4
          ports:
            - containerPort: 8300
            - containerPort: 8301
            - containerPort: 8302
            - containerPort: 8500
            - containerPort: 8600
          volumeMounts:
            - name: consul-1-data
              mountPath: /consul/data
          args: ["agent", "-server", "-bootstrap-expect=3", "-ui", "-client=0.0.0.0"]
          readinessProbe:
            httpGet:
              path: /v1/status/leader
              port: 8500
            initialDelaySeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /v1/status/leader
              port: 8500
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: consul-1-data
          persistentVolumeClaim:
            claimName: consul-1-data

